/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.WorkSpaceProfiles.OrderManagement;

/**
 *
 * @author vish
 */
public class ManageProductPerformaceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProductPerformaceJPanel
     */
    public ManageProductPerformaceJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPTitle = new javax.swing.JLabel();
        lblPName = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        lblPFreqAbv = new javax.swing.JLabel();
        txtPFreqAbv = new javax.swing.JTextField();
        lblPFreqBel = new javax.swing.JLabel();
        txtPFreqBel = new javax.swing.JTextField();
        lblPSalesRev = new javax.swing.JLabel();
        txtPSalesRev = new javax.swing.JTextField();
        lblPMargin = new javax.swing.JLabel();
        txtPMargin = new javax.swing.JTextField();
        btnPBack = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        lblPTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPTitle.setText("Product Performance Summary");

        lblPName.setText("Product Name");

        txtPName.setBackground(java.awt.Color.lightGray);

        lblPFreqAbv.setText("Frequency Above Target");

        txtPFreqAbv.setBackground(java.awt.Color.lightGray);

        lblPFreqBel.setText("Frequency Below Target");

        txtPFreqBel.setBackground(java.awt.Color.lightGray);

        lblPSalesRev.setText("Sales Revenue");

        txtPSalesRev.setBackground(java.awt.Color.lightGray);

        lblPMargin.setText("Margin Around Target");

        txtPMargin.setBackground(java.awt.Color.lightGray);

        btnPBack.setBackground(new java.awt.Color(147, 215, 255));
        btnPBack.setText("< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPMargin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPFreqBel)
                                .addComponent(lblPFreqAbv)
                                .addComponent(lblPName))
                            .addComponent(lblPSalesRev, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPFreqBel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPFreqAbv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPSalesRev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPTitle)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPName)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPFreqAbv)
                    .addComponent(txtPFreqAbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPFreqBel)
                    .addComponent(txtPFreqBel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPSalesRev)
                    .addComponent(txtPSalesRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPMargin)
                    .addComponent(txtPMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnPBack)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPBack;
    private javax.swing.JLabel lblPFreqAbv;
    private javax.swing.JLabel lblPFreqBel;
    private javax.swing.JLabel lblPMargin;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPSalesRev;
    private javax.swing.JLabel lblPTitle;
    private javax.swing.JTextField txtPFreqAbv;
    private javax.swing.JTextField txtPFreqBel;
    private javax.swing.JTextField txtPMargin;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPSalesRev;
    // End of variables declaration//GEN-END:variables
}
